_BASE_: "../../Base-RCNN-FPN.yaml"
MODEL:
  PIXEL_STD: [57.375, 57.120, 58.395]
  BACKBONE:
    NAME: "build_regnetx_fpn_backbone"
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHTS: "/home/leiyvtian/RAL/wsoe/detection/data/VOC-Detection/faster-rcnn/regnetx/regnetx_detectron2.pth"
#  PROPOSAL_GENERATOR:
#    NAME: "RPNLogistic"
  FPN:
    IN_FEATURES: ["s1", "s2", "s3", "s4"]
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NAME: "StandardROIHeads"
    NUM_CLASSES: 20
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('voc_custom_train',)
  TEST: ('voc_custom_val',)
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.004
  STEPS: (48000, 64000)
  MAX_ITER: 72000  # 17.4 epochs
  WARMUP_ITERS: 400
  CHECKPOINT_PERIOD: 12000
DATALOADER:
    NUM_WORKERS: 0  # Depends on the available memory