_BASE_: "../../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNNLogisticWSSTOE"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"

  PROPOSAL_GENERATOR:
    NAME: "RPN_OE"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NAME: "ROIHeadsLogisticWSOEBOXST"
    NUM_CLASSES: 20
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('voc_custom_train',)
  TEST: ('voc_custom_val',)
AUXI_DATASETS:
  TRAIN: ('ImageNet1k_Val_NonoverlapOE',)
  ID_OD_RATIO: 0.5
  START_FINETUNE_ITER: 0
  NUM_CLASSES: 20
  BATCH_SIZE_PER_IMAGE: 128
  POSITIVE_FRACTION: 1
  SUBSET: 16000
SELF_TRAINING:
  NUM_ROUNDS: 5
  ITERATIONS_PER_ROUND: 12000
  KC_POLICY: 'GT'
  KC_VALUE: 'energy_score'
  INIT_OE_PORTION: 1.0
  MIN_OE_PORTION: 0.8
  OE_PORTION_STEP: 0.05
  RAW_RESULTS_PATH: 'raw_results_file'
  FILTERED_RESULTS_PATH: 'filtered_results_file'
  PSEUDO_LABEL_SAVED_PATH: "ImageNet1k_Val_OE_Pseudo_Label"
  LABEL_PATH: 'true_label_file'

SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.004
  STEPS: (48000, 96000)
  MAX_ITER: 104000
  WARMUP_ITERS: 400
  CHECKPOINT_PERIOD: 12000
  LOSS_WEIGHT: 0.2

DATALOADER:
    NUM_WORKERS: 0  # Depends on the available memory